### PR TITLE
remove broken redirects

### PR DESCRIPTION
**Pull request by r10s**
the destination does not exist
and the very broad rule also makes images as
`assets/badges/apklis.png` impossible,
see <https://github.com/deltachat/deltachat-pages/pull/549>

### CODE REVIEW

**Review by missytake — APPROVED** [review]
The change also needs to be deployed of course. Can you do it yourself or should I do it?

**Comment by r10s** [comment]
> Can you do it yourself or should I do it?

please do it for me :) i have no idea about how to deploy things here :)

**Comment by missytake** [comment]
done :)

**Comment by r10s** [comment]
great, thanks!

**Pull request merged**
